### ISSUE TITLE
Setup a Frontend for todo project

### ISSUE THREAD

**Issue by palakgupta2712** [Real-Dev-Squad/todo-frontend#1]
### Issue Description
Setup the frontend for the todo project

[ ] NextJs
[ ] Vitest for testing 
[ ] Tailwind & Shadcn/UI for styling

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.
