### ISSUE TITLE
Feature: Todo Tasks Listing UI

### ISSUE THREAD

**Issue by VaibhavSingh8** [Real-Dev-Squad/todo-frontend#5]
### Issue Description

For the Todo project UI, the Task page should have a tasks section that lists the ToDo and In-progress tasks.
Hence, UI needs to be implemented based on the design mentioned in the screenshots section.

### Expected Behavior

The Tasks page should have a tasks section that lists the ToDo and In-progress tasks.

### Current Behavior

No UI has been implemented yet.

### Screenshots

Proposed Design:

![Todo-listing](https://github.com/user-attachments/assets/8e8066cd-bb7f-4775-90c4-a6488c08ea9e)

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
Setup the Project and verify that no UI is present

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.
